version: "3"

services:

  proxy:
    image: traefik:2.0
    command:
      #- --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - ${DEV_HTTP_PORT-3000}:80
      - ${DEV_TRAEFIK_UI_PORT-3001}:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
   
  client-dev:
    build:
      context: .
      dockerfile: docker/node-dev/Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.client-dev.entrypoints=web
      - traefik.http.routers.client-dev.rule=PathPrefix(`/`)
      - traefik.http.services.client-dev.loadbalancer.server.port=3000
    volumes:
      - ./client:/app

  server-dev:
    build:
      context: .
      dockerfile: docker/node-dev/Dockerfile
    environment:
      APP_BASE_URL: http://localhost:${DEV_HTTP_PORT-3000}
      SMTP_HOST: smtp
      SMTP_PORT: 25
      DB_HOST: pg-dev
      DB_PASSWORD: ${DB_PASSWORD-server-dev-test-password}
      DB_NAME: ${DB_NAME-server-dev-db} 
    labels:
      - traefik.enable=true
      - traefik.http.routers.server-dev.entrypoints=web
      - traefik.http.routers.server-dev.rule=PathPrefix(`/auth`) || PathPrefix(`/graphql`)
      - traefik.http.services.server-dev.loadbalancer.server.port=3001
    volumes:
      - ./server:/app

  smtp:
    image: namshi/smtp
    logging:
          driver: none

  pg-dev:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD-server-dev-test-password}
      POSTGRES_DB: ${DB_NAME-server-dev-db}
