version: "3"

services:
   
  client:
    image: ${CLIENT_IMAGE_NAME}
    build:
      context: .
      dockerfile: docker/node-prod/Dockerfile
      args:
        DIRECTORY: ./client

  server:
    image: ${SERVER_IMAGE_NAME}
    build:
      context: .
      dockerfile: docker/node-prod/Dockerfile
      args:
        DIRECTORY: ./server

