version: "3"

services:
   
  client:
    image: egnf/web-project-template-client
    build:
      context: .
      dockerfile: docker/node-prod/Dockerfile
      args:
        DIRECTORY: ./client

  server:
    image: egnf/web-project-template-server
    build:
      context: .
      dockerfile: docker/node-prod/Dockerfile
      args:
        DIRECTORY: ./server

