version: "3"

services:

  server-test:
    build: docker/node-dev
    environment:
      APP_BASE_URL: http://localhost:${DEV_HTTP_PORT-3000}
      DB_HOST: pg-test
      DB_PASSWORD: ${DB_PASSWORD-server-dev-password}
      DB_NAME: ${DB_NAME-server-dev-db} 
    volumes:
      - ./server:/app
      - ./shared:/shared

  couchdb-test:
    build: docker/couchdb-dev
    environment:
      COUCHDB_USER: ${COUCHDB_USER-couchdb-dev-user}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD-couchdb-dev-password}

  pg-test:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD-server-dev-password}
      POSTGRES_DB: ${DB_NAME-server-dev-db}
